export interface Product {
    id: string;
    name: string;
    description: string;
    imageUrl: string;
    categoryId: string;
    featured: boolean;
    price: number;
    currency: string;
}

export interface Category {
    id: string;
    name: string;
}

export interface CartItem {
    id: string; // generated by backend for the item entry
    productId: string;
    name: string;
    description?: string;
    imageUrl: string;
    price: number;
    currency: string;
    quantity: number;
}

export interface Cart {
    id: string;
    items: CartItem[];
    total: number; // usually calculated by frontend or provided by backend
}

export interface CheckoutResponse {
    orderId: string;
    newCartId: string;
    status: string;
}
